name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run SonarScanner
        run: |
          sonar-scanner-6.2.1.4610\bin\sonar-scanner.bat ^
            -Dsonar.projectKey=AhmedFatrah2001_MA-ID-Server_5807ab0b-fa84-43a2-a407-5438da6d2e18 ^
            -Dsonar.sources=. ^
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} ^
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
